#!/bin/zsh
function mambas() {
  environments=$(eval mamba env list | rg -v '^#|base' | cut -d ' ' -f 1) #  | rg -v '^[\#|base]' | cut -d ' ' -f 1)
  items=("base" "deactivate" "$environments")

  # config for fuzzy finder selection window
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt="🐍 Mamba Config >> " --height=50% --info=inline --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
  mambastatus="Changed Nothing"
  elif [[ $config == "deactivate" ]]; then
    mamba deactivate
  mambastatus="Deactivated"
  else
    mamba activate "$config"
  mambastatus="Activated $config"
  fi
  printf "%s\n" "$mambastatus"
  echo # final newline to show status in shell
  zle accept-line
}
zle -N mambas

function yazicdonquit() {
    tmp="$(mktemp -t "yazi-cwd.XXXXX")"
    ~/Downloads/yazi/target/release/yazi . --cwd-file="$tmp"
    if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[2 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[6 q'
  fi
}
zle -N zle-keymap-select

_fix_cursor() {
   echo -ne '\e[6 q'
}
