#!/usr/bin/env zsh
# Setting up vi mode for ZSH

bindkey -v
export KEYTIMEOUT=1

bindkey -v '^?' backward-delete-char

# Fix Cursor
vi_cursor_mode
precmd_functions+=(zle-line-init) # Change default Cursor
