#!/usr/bin/env zsh
# Setting up vi mode for ZSH

bindkey -v
export KEYTIMEOUT=1

bindkey -v '^?' backward-delete-char

# Fix Cursor
vi_cursor_mode
precmd_functions+=(zle-line-init) # Change default Cursor

# Edit line in vim with v in Normal mode:
autoload -Uz edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Add some vim Text objects
autoload -Uz select-bracketed select-quoted; zle -N select-quoted; zle -N select-bracketed
for km in viopp visual; do
  bindkey -M $km -- '-' vi-up-line-or-history
  for c in {a,i}${(s..)^:-\'\"\`\|,./:;=+@}; do
    bindkey -M $km $c select-quoted
  done
  for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
    bindkey -M $km $c select-bracketed
  done
done
