#!/usr/bin/env zsh
# Setting up vi mode for ZSH

bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu: Broken?
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Fix Cursor
vi_cursor_mode
precmd_functions+=(zle-line-init) # Change default Cursor
