#!/usr/bin/env zsh
# Alias definitions

#cd aliases
alias ..='builtin cd ..'
alias ...='builtin cd ../..'
alias ....='builtin cd ../../..'
alias .4='builtin cd ../../../../'
alias .5='builtin cd ../../../../..'

# ls/eza aliases
alias l='eza'
alias ll='eza -lah --git --icons=always --colour-scale=size'
alias lll='eza -lah --git --icons=always --colour-scale=size --time-style=long-iso'
alias la='eza -ah'
alias lD='eza -lh --only-dirs'
alias lDD='eza -lah --only-dirs'
alias lF='eza -lh --only-files'
alias lFF='eza -lah --only-files'
alias lt='eza -Th --level=2'
alias ltt='eza -Tha --level=2'

# yazi
alias y="yazicdonquit"

# WSL2/Windows
alias reveal="explorer.exe ." # Reveal current dir in File explorer
alias shutdown="wsl.exe --terminate archlinux"

# configs
alias zshconf="nvim ~/minfiles/.homedir/.config/zsh/.zshrc"
alias zshenv="nvim ~/minfiles/.homedir/.zshenv"
alias updateconf="nvim ~/minfiles/scripts/update.zsh"
alias p10kconf="nvim ~/minfiles/.homedir/.config/zsh/.p10k.zsh"
alias aliasconf="nvim ~/minfiles/.homedir/.config/zsh/zsh-aliases" # <- this file

# make
alias remake='make clean && make'

# count files
alias count='find . -type f | wc -l'

# list files/dir by size
alias dust='du -sh * | sort -hr'

# rsync aliases
alias rsync-copy="rsync -avz --progress -h"
alias rsync-move="rsync -avz --progress -h --delete-source-files"
alias rsync-update="rsync -avzu --progress -h"
alias rsync-update="rsync -avzu --delete --progress -h"


## Setup (rip)grep to show colors by default
alias rg='rg --color=auto'
alias grep='grep --color=auto'

# Git
alias gis="git status"
alias gss="git status -s"
alias gid="git diff"
alias gilg="git lg"
alias glog="git log"
alias gsub="git submodule update --remote --rebase"

# vim
alias vim=nvim
alias vi=nvim

# texlive
alias updatetl="tlmgr update --self --all --reinstall-forcibly-removed"

# File manipulation
alias rm="rm -iv"
alias cp="cp -iv"
alias mv="mv -iv"

# misc
alias update="zsh ~/minfiles/scripts/update.zsh"
alias lg="lazygit"
alias bcd="builtin cd"
alias pse="zsh ~/minfiles/scripts/pse.zsh"
alias deleteCompDump="rm ${ZDOTDIR}/.zcompdump"
